export const ROUTER_APP = {
  HOME: "/home",
  PRODUCT: "/product",
  DETAIL: "/product/:id",
  PROFILE: "/profile",
  NEW_PRODUCT: "/newproduct",
  LOGIN_PAGE: "/login",
  REGISTER_PAGE: "/register",
  CHANGEPASSWORD: "/change-password",
  CHANGEINFO: "/change-info",
  HISTORY: "/history",
  ADDCART: "/addcart",
  CHECKOUT: "/checkout",
  SUCCESSCHECKOUT: "/success",
};
